config/routes.rb
Rails.application.routes.draw do
  get '/', to: redirect("https://www.coderfactoryacademy.edu.au")
  constraints(:host => /coderfactoryacademy.com/) do
    get "/(*path)" => redirect {|params, req| "https://www.coderfactoryacademy.edu.au/#{params[:path]}"},  via: [:get]
  end
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # You can have the root of your site routed with "root"
  root "home#index"
  get 'sitemap.xml', :to => 'sitemap#index', :defaults => {:format => 'xml'}

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'
  resources :academy_applications
  get "apply"         => "academy_applications#new"

  resources :enquiries
  get "enquire"       => "enquiries#new"

  resources :expo_attendees
  # get "expo"          => "expo_attendees#new"

  resources :women_in_tech_scholarships
  get "women-in-tech/apply"   => "women_in_tech_scholarships#new"
  get "women-in-tech"         => "pages#women_in_tech_scholarship"

  resources :course_intakes

  resources :posts

  get "workshop-sessions"       =>  "workshop_dates#index"
  get "workshop-sessions/new"   =>  "workshop_attendees#new"
  resources :workshop_attendees
  resources :workshop_dates

  get "information-sessions"      => "info_session_dates#index"
  get "information-sessions/new"  => "info_session_attendees#new"
  resources :info_session_attendees
  resources :info_session_dates

  get "frequently-asked-questions"                => "pages#faq"
  get "curriculum"                                => "pages#curriculum"
  get "about-coder-factory-academy"               => "pages#about"
  get "about-coder-factory-academy/instructors"   => "pages#instructors"
  get "contact"                                   => "pages#contact"
  get "privacy"                                   => "pages#privacy"
  get "confirmation"                              => "pages#confirmation"
  get "vet-fee-help"                              => "pages#vet_fee_help"
  get "partners"                                  => "pages#partners"
  get "testimonials"                              => "pages#testimonials"
  get "video-archive"                             => "pages#video_archive"
  get "career-outcomes"                           => "pages#careers"

  get "blog"          => "blog#index"
  get "press"         => "press#index"

  get "update-spreadsheet"        => "update_spreadsheet#update"
  get "update-expo-spreadsheet"   => "update_spreadsheet#expo_update"
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user

  mount_uploader :image, ImageUploader

  extend FriendlyId
    friendly_id :title, use: :slugged

  validates :title, :lead, :content, :published_date, presence: true


  def self.current_articles
    reverse_chron_order.where("published_date <= ?", Date.today)
  end

  # def self.published_in_reverse_chron_order
    # reverse_chron_order.where(publish: true)
  # end

  def self.reverse_chron_order
    published?.order(published_date: :desc)
  end

  def self.published?
    where(publish: true)
  end

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |post|
        csv << post.attributes.values_at(*column_names)
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user! , only: [:index, :new, :create, :edit, :update, :destroy]

  def index
    @posts = current_user.posts.paginate(:page => params[:page], :per_page => 10)
    @csv_posts = Post.all

    respond_to do |format|
      format.html
      format.csv { send_data @csv_posts.to_csv}
    end
  end

  def new
    @post = Post.new
    respond_with(@post)
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to @post
    else
      respond_with(@post)
    end
  end

  def edit
    @post = Post.friendly.find(params[:id])
  end

  def update
    @post = Post.friendly.find(params[:id])
    if @post.update_attributes(post_params)
      redirect_to @post
    else
      repsond_with(@post)
    end
  end

  def destroy
    @post = Post.friendly.find(params[:id])
    @post.destroy
    redirect_to "/posts"
  end

  def show
    @post = Post.friendly.find(params[:id])
    @info_sessions = InfoSessionDate.all
    @info_session_dates = Array.new
    @info_sessions.each do |session|
      @info_session_dates << session.session_date.strftime('%d %B %Y') if session.session_date.future?
    end
    @info_session_dates.sort! { |a,b|  DateTime.parse(a) <=> DateTime.parse(b) }
    @info_session_date = Array.new
    @info_session_date << @info_session_dates.first
  end

  private
  def post_params
    params.require(:post).permit(:title, :lead, :content, :image, :publish, :published_date)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
  <%= f.error_notification %>
  <div class="form-inputs">
    <div class="form-group input-field">
      <%= f.input :title %>
    </div>
    <div class="#">
      <div class="file-field input-field gallery_picture">
        <div class="row">
          <div class="col s2">
            <div class="btn black-text">
              <span>Image</span>
              <%= f.file_field :image %>
            </div>
          </div>
          <div class="col s10">
            <input class="file-path validate" type="text" placeholder="Upload an opening image. Can't be empty.">
          </div>
        </div>
      </div>
    </div>
    <div class="form-group input-field">
      <%= f.input :lead, input_html: {class: "form-group materialize-textarea"} %>
    </div>
    <%= f.input :content, input_html: { class: 'ckeditor'} %>
    <div class="form-group input-field">
      <%= f.select :publish, [["Publish", true], ["Don't Publish", false]], input_html: {class: "form-control"} %>
    </div>
    <div>
      <label for="published_date">Date Published</label>
      <%= f.text_field :published_date, class: "datepicker", placeholder: "Select a published date. Can't be empty." %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-large submit-button" %>
  </div>
<% end %>

<script>
$('.ckeditor').ckeditor({
  // optional config
});

$('.datepicker').pickadate({
  selectMonths: true, // Creates a dropdown to control month
  selectYears: 15 // Creates a dropdown of 15 years to control year
});
</script>

app/views/posts/_post.html.erb
<div class="row">
<div class="col s12 m12">
  <div class="card z-depth-3">
    <div class="card-image">
      <%= link_to post_path(post) do %>
        <%= image_tag post.image_url() %>
      <% end %>
    </div>
    <div class="card-content blog-post">
      <%= link_to post_path(post) do %><h1><span class="card-title grey-text text-darken-2"><%= post.title %></span></h1><% end %>
      <div class="chip">
        <% if true %>
          <i class="fa fa-user"></i>
        <% else %>
          <%= image_tag post.user.image_url() %>
        <% end%>
        <%= post.user.first_name if post.user %> <%= post.user.last_name if post.user %>
      </div>
      <div class="chip">
        <%= post.published_date.strftime('%d %B %Y') %>
      </div>
      <hr>
      <p class="flow-text"><%= post.lead %></p>
    </div>
    <div class="card-action">
      <%= link_to "Read more", post %>
    </div>
  </div>
</div>
</div>

app/views/posts/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col s12 m10 offset-m1">
      <p class="flow-text"></p>
      <div class="row">
        <div class="col m12">
          <div class="card">
            <div class="card-content grey-text text-darken-2">
              <span class="card-title grey-text text-darken-2">Edit Blog Post</span>
              <%= render 'form' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<section id="top-section">
<div class="container">
  <div class="row">
    <div class="col m12">
      <h2>Your Posts</h2>
      <div class="card">
        <div class="card-content">
          <%= link_to 'New Post', new_post_path, class: 'btn btn-large submit-button' %>
          <%= link_to 'Download CSV', posts_path(format: "csv") %>
          <table class="table">
            <thead>
              <tr>
                <th width="40%">Title</th>
                <th width="15%">Author</th>
                <th width="10%">Publish</th>
                <th width="15%">Published</th>
                <th>Views</th>
                <th colspan="2"></th>
              </tr>
            </thead>

            <tbody>
              <% @posts.each do |post| %>
                <tr>
                  <td><%= post.title%></td>
                  <td><%= post.user.first_name if post.user %></td>
                  <td><%= '<i class="fa fa-check"></i>'.html_safe if post.publish %></td>
                  <td><%= post.published_date.strftime('%d %B %Y') %></td>
                  <td><%= link_to '<i class="fa fa-eye"></i> View'.html_safe, post %></td>
                  <td><%= link_to '<i class="fa fa-pencil"></i> Edit'.html_safe, edit_post_path(post) %></td>
                  <td><%= link_to '<i class="fa fa-trash-o"></i> Delete'.html_safe, post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <% if @posts.size == 0 %>
            <center>
              <h3>You currently have no posts.<br> Fix this using the "New Post" button located above.</h3>
            </center>
          <% end %>
        </div>
      </div>
      <div class="card">
        <center>
          <%= will_paginate @posts %>
        </center>
      </div>
    </div>
  </div>
</div>
</section>

app/views/posts/new.html.erb
<div class="container">
  <div class="row">
    <div class="col s12 m10 offset-m1">
      <p class="flow-text"></p>
      <div class="row">
        <div class="col m12">
          <div class="card">
            <div class="card-content grey-text text-darken-2">
              <span class="card-title grey-text text-darken-2">New Blog Post</span>
              <%= render 'form' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<%= content_for :title, @post.title + ' [@CoderFactory Blog]' %>
<%= content_for :description, @post.title + ': ' + @post.lead %>
<%= content_for :image, @post.image %>
<%= content_for :tagline, @post.published_date.strftime('%d %B %Y') %>

<section id="top-section">
  <div class="container">
    <div class="row">
      <div class="col m9 s12">
        <div class="card">
          <div class="card-image">
            <%= image_tag @post.image_url() %>
          </div>
          <div class="card-content blog-post">
            <%= link_to post_path(@post) do %><h1><span class="card-title grey-text text-darken-2"><%= @post.title %></span></h1><% end %>
            <div class="chip">
              <% if @post.user.image.nil? %>
                <%= image_tag @post.user.image_url() %>
              <% else %>
                <i class="fa fa-user"></i>
              <% end %>
              <%= @post.user.first_name %> <%= @post.user.last_name %>
            </div>
            <div class="chip">
              <%= @post.published_date.strftime('%d %B %Y') %>
            </div>
            <hr>
            <p class="flow-text"><%= @post.lead %></p>

            <div class="flow-text">
              <%= @post.content.html_safe %>
            </div>
          </div>
        </div>
      </div>
      <div class="col m3 hide-on-small-only">
        <%= render 'blog/side_nav' %>
    </div>
  </div>
</section>